-- Bảng lưu dữ liệu ý tưởng cho 3d-idea-max trên Neon.
--
-- Chạy file này trong Neon SQL Editor SAU KHI đã bật Data API cho branch.
--
-- Chạy xong CÒN MỘT BƯỚC trong Console: Postgres database > Data API > nút
-- "Configure Data API" > đặt Anonymous role = `anonymous`. Thiếu bước đó thì proxy
-- của Neon từ chối mọi request không kèm JWT với lỗi "missing authentication
-- credentials", bất kể quyền cấp trong file này.
--
-- Mô hình: mỗi file JSON trong src/data/json/ là MỘT dòng, nội dung giữ nguyên
-- dạng jsonb. Không tách bảng chuẩn hoá vì toàn bộ type TypeScript hiện có
-- (ProductCategory, AttributeAxis, ...) map thẳng 1-1 với JSON — tách bảng sẽ
-- phải viết lại lớp dữ liệu mà không đổi được gì về tính năng.

-- Role dùng cho request không kèm header Authorization. Data API thường tạo sẵn
-- role này khi bật; tạo ở đây để migration chạy được cả khi chưa có.
-- `nologin` = không đăng nhập Postgres trực tiếp được, chỉ Data API mượn danh.
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anonymous') then
    create role anonymous nologin;
  end if;
end
$$;

create table if not exists idea_documents (
  name       text primary key,
  content    jsonb not null,
  version    integer not null default 1,
  updated_at timestamptz not null default now()
);

-- Lịch sử bản ghi đè. App cho phép BẤT KỲ AI sửa dữ liệu (quyết định của chủ
-- project), nên đây là đường khôi phục duy nhất khi có người ghi đè bừa.
create table if not exists idea_document_history (
  id          bigint generated by default as identity primary key,
  name        text not null,
  content     jsonb not null,
  version     integer not null,
  replaced_at timestamptz not null default now()
);

create index if not exists idea_document_history_name_idx
  on idea_document_history (name, replaced_at desc);

-- Tăng version + đóng dấu thời gian ở phía server. Client không tự đặt được
-- version, nhờ đó khoá lạc quan (optimistic lock) bên dưới mới đáng tin.
-- SECURITY DEFINER: role anonymous không có quyền trên bảng history, chỉ trigger
-- này (chạy bằng quyền owner) được ghi vào đó.
create or replace function idea_documents_on_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into idea_document_history (name, content, version)
  values (old.name, old.content, old.version);

  -- Giữ 20 bản gần nhất mỗi document — đủ để lùi lại, không phình storage
  delete from idea_document_history
  where id in (
    select id from idea_document_history
    where name = old.name
    order by replaced_at desc
    offset 20
  );

  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists idea_documents_before_update on idea_documents;
create trigger idea_documents_before_update
  before update on idea_documents
  for each row execute function idea_documents_on_update();

-- ---------------------------------------------------------------------------
-- Quyền cho truy cập ẩn danh (không cần đăng nhập)
--
-- Request tới Data API không kèm header Authorization sẽ chạy dưới role
-- `anonymous`; mặc định role này KHÔNG có quyền nào.
-- Nguồn: https://neon.com/docs/data-api/manage
--
-- Cố ý KHÔNG cấp DELETE: xoá dòng là thao tác không có đường lùi, còn ghi đè
-- thì trigger phía trên đã lưu lại bản cũ.
-- ---------------------------------------------------------------------------
grant usage on schema public to anonymous;
grant select, insert, update on idea_documents to anonymous;

alter table idea_documents enable row level security;
alter table idea_document_history enable row level security;
-- Không tạo policy nào cho idea_document_history: RLS bật + không policy =
-- chặn sạch. Chỉ đọc được qua SQL Editor bằng role owner.

drop policy if exists idea_documents_read on idea_documents;
create policy idea_documents_read on idea_documents
  for select to anonymous
  using (true);

-- Giới hạn `name` trong đúng 7 file dữ liệu của app: người lạ không đổ thêm
-- dòng rác vào bảng được.
drop policy if exists idea_documents_insert on idea_documents;
create policy idea_documents_insert on idea_documents
  for insert to anonymous
  with check (
    name in (
      'categories', 'attributes', 'technicalAxes',
      'mechanisms', 'characters', 'personalizations', 'fusionFormulas'
    )
  );

drop policy if exists idea_documents_update on idea_documents;
create policy idea_documents_update on idea_documents
  for update to anonymous
  using (true)
  with check (
    name in (
      'categories', 'attributes', 'technicalAxes',
      'mechanisms', 'characters', 'personalizations', 'fusionFormulas'
    )
  );
